LOCAL_PATH := $(call my-dir)

#QP Gallery
include $(CLEAR_VARS)
LOCAL_MODULE := QPGallery
LOCAL_PRIVILEGED_MODULE := true
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := priv-app/QPGallery/QPGallery.apk
LOCAL_MODULE_CLASS := APPS
LOCAL_OVERRIDES_PACKAGES := Gallery2 Gallery3d Gallery SnapdragonGallery
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_PATH := $(TARGET_OUT)/priv-app
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
include $(BUILD_PREBUILT)

#Pulse Music
include $(CLEAR_VARS)
LOCAL_MODULE := PulseMusic
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := PulseMusic/PulseMusic.apk
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_MODULE_PATH := $(TARGET_OUT)/priv-app
LOCAL_OVERRIDES_PACKAGES := Music
include $(BUILD_PREBUILT)
